/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_iflytek_yyplusdemo_myjni_MyJni */

#ifndef _Included_com_pjx_mvvmdemo_myjni_MyJni
#define _Included_com_pjx_mvvmdemo_myjni_MyJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_iflytek_yyplusdemo_myjni_MyJni
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pjx_mvvmdemo_myjni_MyJni_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
